// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: drone/drone.proto

package dronepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DroneService_StreamPositions_FullMethodName   = "/drone.DroneService/StreamPositions"
	DroneService_GetCurrentState_FullMethodName   = "/drone.DroneService/GetCurrentState"
	DroneService_GetHistory_FullMethodName        = "/drone.DroneService/GetHistory"
	DroneService_ControlSimulation_FullMethodName = "/drone.DroneService/ControlSimulation"
)

// DroneServiceClient is the client API for DroneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DroneServiceClient interface {
	// Realtime streaming RPC
	StreamPositions(ctx context.Context, in *GetCurrentStateRequest, opts ...grpc.CallOption) (DroneService_StreamPositionsClient, error)
	// Query current state
	GetCurrentState(ctx context.Context, in *GetCurrentStateRequest, opts ...grpc.CallOption) (*GetCurrentStateResponse, error)
	// Query get history of drone
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// Set up config simulator
	ControlSimulation(ctx context.Context, in *SimulationConfigRequest, opts ...grpc.CallOption) (*SimulationConfigResponse, error)
}

type droneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDroneServiceClient(cc grpc.ClientConnInterface) DroneServiceClient {
	return &droneServiceClient{cc}
}

func (c *droneServiceClient) StreamPositions(ctx context.Context, in *GetCurrentStateRequest, opts ...grpc.CallOption) (DroneService_StreamPositionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DroneService_ServiceDesc.Streams[0], DroneService_StreamPositions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &droneServiceStreamPositionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DroneService_StreamPositionsClient interface {
	Recv() (*DronePositionUpdate, error)
	grpc.ClientStream
}

type droneServiceStreamPositionsClient struct {
	grpc.ClientStream
}

func (x *droneServiceStreamPositionsClient) Recv() (*DronePositionUpdate, error) {
	m := new(DronePositionUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *droneServiceClient) GetCurrentState(ctx context.Context, in *GetCurrentStateRequest, opts ...grpc.CallOption) (*GetCurrentStateResponse, error) {
	out := new(GetCurrentStateResponse)
	err := c.cc.Invoke(ctx, DroneService_GetCurrentState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, DroneService_GetHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *droneServiceClient) ControlSimulation(ctx context.Context, in *SimulationConfigRequest, opts ...grpc.CallOption) (*SimulationConfigResponse, error) {
	out := new(SimulationConfigResponse)
	err := c.cc.Invoke(ctx, DroneService_ControlSimulation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DroneServiceServer is the server API for DroneService service.
// All implementations must embed UnimplementedDroneServiceServer
// for forward compatibility
type DroneServiceServer interface {
	// Realtime streaming RPC
	StreamPositions(*GetCurrentStateRequest, DroneService_StreamPositionsServer) error
	// Query current state
	GetCurrentState(context.Context, *GetCurrentStateRequest) (*GetCurrentStateResponse, error)
	// Query get history of drone
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// Set up config simulator
	ControlSimulation(context.Context, *SimulationConfigRequest) (*SimulationConfigResponse, error)
	mustEmbedUnimplementedDroneServiceServer()
}

// UnimplementedDroneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDroneServiceServer struct {
}

func (UnimplementedDroneServiceServer) StreamPositions(*GetCurrentStateRequest, DroneService_StreamPositionsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPositions not implemented")
}
func (UnimplementedDroneServiceServer) GetCurrentState(context.Context, *GetCurrentStateRequest) (*GetCurrentStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentState not implemented")
}
func (UnimplementedDroneServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedDroneServiceServer) ControlSimulation(context.Context, *SimulationConfigRequest) (*SimulationConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ControlSimulation not implemented")
}
func (UnimplementedDroneServiceServer) mustEmbedUnimplementedDroneServiceServer() {}

// UnsafeDroneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DroneServiceServer will
// result in compilation errors.
type UnsafeDroneServiceServer interface {
	mustEmbedUnimplementedDroneServiceServer()
}

func RegisterDroneServiceServer(s grpc.ServiceRegistrar, srv DroneServiceServer) {
	s.RegisterService(&DroneService_ServiceDesc, srv)
}

func _DroneService_StreamPositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetCurrentStateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DroneServiceServer).StreamPositions(m, &droneServiceStreamPositionsServer{stream})
}

type DroneService_StreamPositionsServer interface {
	Send(*DronePositionUpdate) error
	grpc.ServerStream
}

type droneServiceStreamPositionsServer struct {
	grpc.ServerStream
}

func (x *droneServiceStreamPositionsServer) Send(m *DronePositionUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _DroneService_GetCurrentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).GetCurrentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_GetCurrentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).GetCurrentState(ctx, req.(*GetCurrentStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DroneService_ControlSimulation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DroneServiceServer).ControlSimulation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DroneService_ControlSimulation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DroneServiceServer).ControlSimulation(ctx, req.(*SimulationConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DroneService_ServiceDesc is the grpc.ServiceDesc for DroneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DroneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drone.DroneService",
	HandlerType: (*DroneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentState",
			Handler:    _DroneService_GetCurrentState_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _DroneService_GetHistory_Handler,
		},
		{
			MethodName: "ControlSimulation",
			Handler:    _DroneService_ControlSimulation_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPositions",
			Handler:       _DroneService_StreamPositions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "drone/drone.proto",
}
